USE SMARTBUY

GO
IF(OBJECT_ID ('SP_INS_FACTURA', 'P')) IS NOT NULL
    DROP PROCEDURE SP_INS_FACTURA;

GO
CREATE PROCEDURE SP_INS_FACTURA
	@USERNAME NVARCHAR(25),
	@FECHA DATETIME,
	@SUBTOTAL MONEY,
	@IMPUESTO MONEY,
	@TOTAL MONEY
AS
BEGIN
	BEGIN TRANSACTION 
		BEGIN TRY
			INSERT INTO FACTURAS(USERNAME,FECHA,SUBTOTAL,IMPUESTO,TOTAL)
			VALUES(@USERNAME,@FECHA,@SUBTOTAL,@IMPUESTO,@TOTAL)

			COMMIT TRANSACTION
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION
			SELECT ERROR_MESSAGE() AS [Error Message] 
		END CATCH
END

GO
IF(OBJECT_ID('SP_INS_DETALLE','P')) IS NOT NULL
	DROP PROCEDURE SP_INS_DETALLE
GO
CREATE PROCEDURE SP_INS_DETALLE
	@ID_FACTURA INT,
	@ID_PRODUCTO INT,
	@NOMBRE_PRODUCTO NVARCHAR(25),
	@CANTIDAD_PRODUCTO INT,
	@PRECIO_PRODUCTO MONEY,
	@TOTAL MONEY
AS
BEGIN
	BEGIN TRANSACTION
		BEGIN TRY
			INSERT INTO DETALLE(ID_FACTURA,ID_PRODUCTO,NOMBRE_PRODUCTO,CANTIDAD_PRODUCTO,PRECIO_PRODUCTO,TOTAL)
			VALUES(@ID_FACTURA,@ID_PRODUCTO,@NOMBRE_PRODUCTO,@CANTIDAD_PRODUCTO,@PRECIO_PRODUCTO,@TOTAL)

			COMMIT TRANSACTION
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION
			SELECT ERROR_MESSAGE() AS [Error Message] 
		END CATCH
END