USE SMARTBUY
UPDATE USUARIOS SET ID_ROL = 'A' where USERNAME = 'Fer9606'


INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('Adidas')

INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('Nike')

INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('Reebok')

INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('Levis')

INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('Converse')

INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('NewBalance')

INSERT INTO MARCA(NOMBRE_MARCA)
VALUES('Elemet')

SELECT * FROM USUARIOS
SELECT * FROM PRODUCTOS
SELECT * FROM MARCA
SELECT * FROM WISHLIST

DELETE FROM USUARIOS WHERE USERNAME = ''

DELETE WISHLIST
DBCC CHECKIDENT (WISHLIST,RESEED,0)