--STORED PROCEDURES USUARIO
---CREAR USUARIO*
---EDITAR*
---ELIMINAR(DESACTIVAR ESTADO)*
---LOGIN (LEFT JOIN)*

--STORED PROCEDURES PRODUCTOS
---INSERTAR PRODUCTOS*
---INVENTARIO*
---EDITAR PRODUCTOS*

--STORED PROCEDURES FACTURA
---CREAR FACTURA
---EDITAR FACTURA*(DUDA)
---ELIMINAR FACTURA

--STORED PROCEDURES DETALLE
---CREAR DETALLE
---EDITAR DETALLE
---ELIMINAR DETALLE


--TRIGGERS PRODUCTOS
---UPDATE PRODUCTOS INVENTARIOS(CANTIDAD,NOMBRE, PRECIO)