USE SMARTBUY

GO
IF(OBJECT_ID ('SP_INS_NUEVO_USUARIO', 'P')) IS NOT NULL
    DROP PROCEDURE SP_INS_NUEVO_USUARIO;
GO
CREATE PROCEDURE SP_INS_NUEVO_USUARIO
	@USERNAME NVARCHAR(25) ,
	@PASSWORD NVARCHAR(15),
	@NOMBRE NVARCHAR(25),
	@APELLIDOS NVARCHAR(50),
	@CEDULA NVARCHAR(12),
	@DIRECCION NVARCHAR(70),
	@TELEFONO NVARCHAR(12),
	@CORREO_ELECTRONICO NVARCHAR(50),
	@FOTO IMAGE,
	@ESTADO BIT,
	@ROL NVARCHAR(1)
AS 
    BEGIN
        IF EXISTS (SELECT USERNAME FROM USUARIOS(NOLOCK) WHERE USERNAME = @USERNAME)
        BEGIN    
            PRINT 'EL USUARIO YA EXISTE INTENTE CON OTRO USUARIO'
        END
        ELSE 
            BEGIN
				BEGIN TRANSACTION
					BEGIN TRY
						INSERT INTO USUARIOS(USERNAME,PASSWORD,NOMBRE,APELLIDOS,CEDULA,DIRECCION,TELEFONO,CORREO_ELECTRONICO,FOTO,ESTADO)
						VALUES(@USERNAME,@PASSWORD,@NOMBRE,@APELLIDOS,@CEDULA,@DIRECCION,@TELEFONO,@CORREO_ELECTRONICO,@FOTO,@ESTADO)

						INSERT INTO ROL(USERNAME,ROL)
						VALUES(@USERNAME,@ROL)

						COMMIT TRANSACTION
					END TRY
					BEGIN CATCH
						ROLLBACK TRANSACTION
						SELECT ERROR_MESSAGE() AS [Error Message]
					END CATCH
            END
    END

------------------------------
 GO
IF(OBJECT_ID ('LOGING', 'P')) IS NOT NULL
    DROP PROCEDURE LOGING;
GO
CREATE PROCEDURE LOGING
	@USERNAME NVARCHAR(25),
	@PASSWORD NVARCHAR(15)
AS
    BEGIN
        IF EXISTS(SELECT USERNAME, PASSWORD FROM USUARIOS WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD)
        BEGIN
			BEGIN TRY
				SELECT ROL,NOMBRE,APELLIDOS,FOTO,ESTADO FROM USUARIOS U JOIN ROL R
				ON U.USERNAME = R.USERNAME
			END TRY
			BEGIN CATCH
				SELECT ERROR_MESSAGE() AS [Error Message]
			END CATCH
        END
        ELSE
        BEGIN
            PRINT 'USUARIO O CONTRASEÑA INCORRECTOS'
        END
    END

------------------------------
GO
IF(OBJECT_ID ('MODIDIFICAR_USUARIO', 'P')) IS NOT NULL
    DROP PROCEDURE MODIDIFICAR_USUARIO;
GO
CREATE PROCEDURE MODIDIFICAR_USUARIO
	@USERNAME NVARCHAR(25),
	@PASSWORD NVARCHAR(15),
	@NOMBRE NVARCHAR(25),
	@APELLIDOS NVARCHAR(50),
	@CEDULA NVARCHAR(12),
	@DIRECCION NVARCHAR(70),
	@TELEFONO NVARCHAR(12),
	@CORREO_ELECTRONICO NVARCHAR(50),
	@FOTO IMAGE,
	@ESTADO BIT
AS 
    BEGIN
		BEGIN TRY
			UPDATE USUARIOS SET PASSWORD=@PASSWORD,NOMBRE=@NOMBRE,APELLIDOS=@APELLIDOS,CEDULA=@CEDULA,DIRECCION=@DIRECCION,
							TELEFONO=@TELEFONO,CORREO_ELECTRONICO= @CORREO_ELECTRONICO,FOTO=@FOTO
			WHERE USERNAME = @USERNAME
		END TRY
		BEGIN CATCH
			SELECT ERROR_MESSAGE() AS [Error Message]
		END CATCH        
    END

------------------------------
GO
IF(OBJECT_ID ('ELIMINAR_USUARIO', 'P')) IS NOT NULL
    DROP PROCEDURE ELIMINAR_USUARIO;
GO
CREATE PROCEDURE ELIMINAR_USUARIO
	@USERNAME NVARCHAR(25)
AS 
    BEGIN
		BEGIN TRY
			DECLARE @ESTADO BIT
				SET @ESTADO = 0
			UPDATE USUARIOS SET ESTADO = @ESTADO WHERE USERNAME = @USERNAME
		END TRY
		BEGIN CATCH
			SELECT ERROR_MESSAGE() AS [Error Message]
		END CATCH
			
    END
