USE SMARTBUY

GO
IF(OBJECT_ID ('NUEVO_PRODUCTO', 'P')) IS NOT NULL
    DROP PROCEDURE NUEVO_PRODUCTO;
GO
CREATE PROCEDURE NUEVO_PRODUCTO
	@ID_PRODUCTO NVARCHAR(9),
	@NOMBRE NVARCHAR(25),
	@MARCA NVARCHAR(25),
	@DETALLE NVARCHAR(50),
	@PRECIO MONEY,
	@CANTIDAD INT,
	@FOTO IMAGE
AS
    BEGIN
        IF EXISTS (SELECT * FROM PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO)
        BEGIN   
            PRINT 'EL ID DEL PRODUCTO YA ESTA REGISTRADO'
        END
        ELSE
            BEGIN
                INSERT INTO PRODUCTOS(ID_PRODUCTO,NOMBRE,MARCA,DETALLE,PRECIO,
                CANTIDAD,FOTO)
                VALUES(@ID_PRODUCTO,@NOMBRE,@MARCA,@DETALLE,@PRECIO,@CANTIDAD,@FOTO)
            END
    END

GO
IF(OBJECT_ID ('EDITAR_PRODUCTO', 'P')) IS NOT NULL
    DROP PROCEDURE EDITAR_PRODUCTO;
GO
CREATE PROCEDURE EDITAR_PRODUCTO
@ID_PRODUCTO NVARCHAR(9),
@NOMBRE NVARCHAR(25),
@MARCA NVARCHAR(25),
@DETALLE NVARCHAR(50),
@PRECIO MONEY,
@CANTIDAD INT,
@FOTO IMAGE
AS
    BEGIN
        UPDATE PRODUCTOS
        SET
            NOMBRE = @NOMBRE,
            MARCA = @MARCA,
            DETALLE = @DETALLE,
            PRECIO = @PRECIO,
            CANTIDAD = @CANTIDAD,
            FOTO = @FOTO
            WHERE ID_PRODUCTO= @ID_PRODUCTO
    END
