CREATE DATABASE SMARTBUY

USE SMARTBUY

CREATE TABLE USUARIOS(
USERNAME NVARCHAR(25) PRIMARY KEY NOT NULL,
PASSWORD NVARCHAR(18) NOT NULL,
NOMBRE NVARCHAR(25) NULL,
APELLIDOS NVARCHAR(50) NULL,
CEDULA NVARCHAR(12) NULL,
DIRECCION NVARCHAR(70) NULL,
TELEFONO NVARCHAR(12) NULL,
CORREO_ELECTRONICO NVARCHAR(50) NULL,
ESTADO BIT DEFAULT(1),--NO SE MUESTRA AL USUARIO
ID_ROL CHAR(1) DEFAULT 'N',
)

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY IDENTITY (1,1),
NOMBRE NVARCHAR(25) NOT NULL,
MARCA NVARCHAR(25) NOT NULL,
CATEGORIA NVARCHAR(15) NOT NULL,
DETALLE NVARCHAR(50) NOT NULL,
PRECIO MONEY NOT NULL,
CANTIDAD INT NOT NULL,
FOTO iMAGE NULL
)

CREATE TABLE MARCA(
ID_MARCA INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_MARCA NVARCHAR(15)
)

CREATE TABLE WISHLIST(
ID_WISH INT PRIMARY KEY IDENTITY(1,1),
USERNAME NVARCHAR(25) FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
ID_PRODUCTO INT FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
NOMBRE NVARCHAR(25) NOT NULL,
MARCA NVARCHAR(25) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO MONEY NOT NULL,
TOTAL MONEY
)


--PROXIMAS ACTUALIZACIONES
CREATE TABLE INVENTARIO(
ID_PRODUCTO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NOMBRE_PRODUCTO VARCHAR(25) NOT NULL,
CANTIDAD_PRODUCTO INT NOT NULL,
)

CREATE TABLE FACTURAS(
ID_FACTURA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
USERNAME NVARCHAR(25)FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
FECHA DATETIME NOT NULL,
SUBTOTAL MONEY NOT NULL,
IMPUESTO MONEY NOT NULL,
TOTAL MONEY NOT NULL
)

CREATE TABLE DETALLE(
ID_DETALLE INT PRIMARY KEY IDENTITY(1,1),
ID_FACTURA INT FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA),
ID_PRODUCTO INT FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
NOMBRE_PRODUCTO NVARCHAR(25) NOT NULL,
CANTIDAD_PRODUCTO INT NOT NULL,
PRECIO_PRODUCTO MONEY NOT NULL,
TOTAL MONEY NOT NULL
)

