//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_SmartBuy.Service_Product {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/Productos")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FOTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PRODUCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PRECIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANTIDAD {
            get {
                return this.CANTIDADField;
            }
            set {
                if ((this.CANTIDADField.Equals(value) != true)) {
                    this.CANTIDADField = value;
                    this.RaisePropertyChanged("CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORIA {
            get {
                return this.CATEGORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORIAField, value) != true)) {
                    this.CATEGORIAField = value;
                    this.RaisePropertyChanged("CATEGORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DETALLE {
            get {
                return this.DETALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLEField, value) != true)) {
                    this.DETALLEField = value;
                    this.RaisePropertyChanged("DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FOTO {
            get {
                return this.FOTOField;
            }
            set {
                if ((object.ReferenceEquals(this.FOTOField, value) != true)) {
                    this.FOTOField = value;
                    this.RaisePropertyChanged("FOTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PRODUCTO {
            get {
                return this.ID_PRODUCTOField;
            }
            set {
                if ((this.ID_PRODUCTOField.Equals(value) != true)) {
                    this.ID_PRODUCTOField = value;
                    this.RaisePropertyChanged("ID_PRODUCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MARCA {
            get {
                return this.MARCAField;
            }
            set {
                if ((object.ReferenceEquals(this.MARCAField, value) != true)) {
                    this.MARCAField = value;
                    this.RaisePropertyChanged("MARCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRECIO {
            get {
                return this.PRECIOField;
            }
            set {
                if ((this.PRECIOField.Equals(value) != true)) {
                    this.PRECIOField = value;
                    this.RaisePropertyChanged("PRECIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://schemas.datacontract.org/2004/07/Productos.Models")]
    [System.SerializableAttribute()]
    public partial class Marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MARCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_MARCAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MARCA {
            get {
                return this.ID_MARCAField;
            }
            set {
                if ((this.ID_MARCAField.Equals(value) != true)) {
                    this.ID_MARCAField = value;
                    this.RaisePropertyChanged("ID_MARCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_MARCA {
            get {
                return this.NOMBRE_MARCAField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_MARCAField, value) != true)) {
                    this.NOMBRE_MARCAField = value;
                    this.RaisePropertyChanged("NOMBRE_MARCA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_Product.IMetodos")]
    public interface IMetodos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/NuevoProducto", ReplyAction="http://tempuri.org/IMetodos/NuevoProductoResponse")]
        void NuevoProducto(string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/NuevoProducto", ReplyAction="http://tempuri.org/IMetodos/NuevoProductoResponse")]
        System.Threading.Tasks.Task NuevoProductoAsync(string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Modificar", ReplyAction="http://tempuri.org/IMetodos/ModificarResponse")]
        void Modificar(int Idproducto, string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Modificar", ReplyAction="http://tempuri.org/IMetodos/ModificarResponse")]
        System.Threading.Tasks.Task ModificarAsync(int Idproducto, string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/BuscarProducto", ReplyAction="http://tempuri.org/IMetodos/BuscarProductoResponse")]
        Web_SmartBuy.Service_Product.Producto[] BuscarProducto(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/BuscarProducto", ReplyAction="http://tempuri.org/IMetodos/BuscarProductoResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto[]> BuscarProductoAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/ProductosMarca", ReplyAction="http://tempuri.org/IMetodos/ProductosMarcaResponse")]
        Web_SmartBuy.Service_Product.Producto[] ProductosMarca(string Marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/ProductosMarca", ReplyAction="http://tempuri.org/IMetodos/ProductosMarcaResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto[]> ProductosMarcaAsync(string Marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/ProductosCategoria", ReplyAction="http://tempuri.org/IMetodos/ProductosCategoriaResponse")]
        Web_SmartBuy.Service_Product.Producto[] ProductosCategoria(string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/ProductosCategoria", ReplyAction="http://tempuri.org/IMetodos/ProductosCategoriaResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto[]> ProductosCategoriaAsync(string Categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Marcas", ReplyAction="http://tempuri.org/IMetodos/MarcasResponse")]
        Web_SmartBuy.Service_Product.Marca[] Marcas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Marcas", ReplyAction="http://tempuri.org/IMetodos/MarcasResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Marca[]> MarcasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/BusquedaId", ReplyAction="http://tempuri.org/IMetodos/BusquedaIdResponse")]
        Web_SmartBuy.Service_Product.Producto BusquedaId(int Id_producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/BusquedaId", ReplyAction="http://tempuri.org/IMetodos/BusquedaIdResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto> BusquedaIdAsync(int Id_producto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetodosChannel : Web_SmartBuy.Service_Product.IMetodos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosClient : System.ServiceModel.ClientBase<Web_SmartBuy.Service_Product.IMetodos>, Web_SmartBuy.Service_Product.IMetodos {
        
        public MetodosClient() {
        }
        
        public MetodosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NuevoProducto(string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto) {
            base.Channel.NuevoProducto(Nombre, Marca, Categoria, Detalle, precio, Cantidad, Foto);
        }
        
        public System.Threading.Tasks.Task NuevoProductoAsync(string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto) {
            return base.Channel.NuevoProductoAsync(Nombre, Marca, Categoria, Detalle, precio, Cantidad, Foto);
        }
        
        public void Modificar(int Idproducto, string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto) {
            base.Channel.Modificar(Idproducto, Nombre, Marca, Categoria, Detalle, precio, Cantidad, Foto);
        }
        
        public System.Threading.Tasks.Task ModificarAsync(int Idproducto, string Nombre, string Marca, string Categoria, string Detalle, decimal precio, int Cantidad, byte[] Foto) {
            return base.Channel.ModificarAsync(Idproducto, Nombre, Marca, Categoria, Detalle, precio, Cantidad, Foto);
        }
        
        public Web_SmartBuy.Service_Product.Producto[] BuscarProducto(string Nombre) {
            return base.Channel.BuscarProducto(Nombre);
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto[]> BuscarProductoAsync(string Nombre) {
            return base.Channel.BuscarProductoAsync(Nombre);
        }
        
        public Web_SmartBuy.Service_Product.Producto[] ProductosMarca(string Marca) {
            return base.Channel.ProductosMarca(Marca);
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto[]> ProductosMarcaAsync(string Marca) {
            return base.Channel.ProductosMarcaAsync(Marca);
        }
        
        public Web_SmartBuy.Service_Product.Producto[] ProductosCategoria(string Categoria) {
            return base.Channel.ProductosCategoria(Categoria);
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto[]> ProductosCategoriaAsync(string Categoria) {
            return base.Channel.ProductosCategoriaAsync(Categoria);
        }
        
        public Web_SmartBuy.Service_Product.Marca[] Marcas() {
            return base.Channel.Marcas();
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Marca[]> MarcasAsync() {
            return base.Channel.MarcasAsync();
        }
        
        public Web_SmartBuy.Service_Product.Producto BusquedaId(int Id_producto) {
            return base.Channel.BusquedaId(Id_producto);
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_Product.Producto> BusquedaIdAsync(int Id_producto) {
            return base.Channel.BusquedaIdAsync(Id_producto);
        }
    }
}
