//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_SmartBuy.Service_User {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Usuario")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEDULAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREO_ELECTRONICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERNAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDOS {
            get {
                return this.APELLIDOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOSField, value) != true)) {
                    this.APELLIDOSField = value;
                    this.RaisePropertyChanged("APELLIDOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEDULA {
            get {
                return this.CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CEDULAField, value) != true)) {
                    this.CEDULAField = value;
                    this.RaisePropertyChanged("CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_ELECTRONICO {
            get {
                return this.CORREO_ELECTRONICOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_ELECTRONICOField, value) != true)) {
                    this.CORREO_ELECTRONICOField = value;
                    this.RaisePropertyChanged("CORREO_ELECTRONICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION {
            get {
                return this.DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONField, value) != true)) {
                    this.DIRECCIONField = value;
                    this.RaisePropertyChanged("DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((this.ESTADOField.Equals(value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_ROL {
            get {
                return this.ID_ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_ROLField, value) != true)) {
                    this.ID_ROLField = value;
                    this.RaisePropertyChanged("ID_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD {
            get {
                return this.PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSWORDField, value) != true)) {
                    this.PASSWORDField = value;
                    this.RaisePropertyChanged("PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_User.IMetodos")]
    public interface IMetodos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/AddClient", ReplyAction="http://tempuri.org/IMetodos/AddClientResponse")]
        bool AddClient(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/AddClient", ReplyAction="http://tempuri.org/IMetodos/AddClientResponse")]
        System.Threading.Tasks.Task<bool> AddClientAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/UpdateInfo", ReplyAction="http://tempuri.org/IMetodos/UpdateInfoResponse")]
        void UpdateInfo(string Username, string Nombre, string Apellidos, string Cedula, string Direccion, string Telefono, string CorreoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/UpdateInfo", ReplyAction="http://tempuri.org/IMetodos/UpdateInfoResponse")]
        System.Threading.Tasks.Task UpdateInfoAsync(string Username, string Nombre, string Apellidos, string Cedula, string Direccion, string Telefono, string CorreoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/StateChange", ReplyAction="http://tempuri.org/IMetodos/StateChangeResponse")]
        void StateChange(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/StateChange", ReplyAction="http://tempuri.org/IMetodos/StateChangeResponse")]
        System.Threading.Tasks.Task StateChangeAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Login", ReplyAction="http://tempuri.org/IMetodos/LoginResponse")]
        Web_SmartBuy.Service_User.Usuario Login(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Login", ReplyAction="http://tempuri.org/IMetodos/LoginResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_User.Usuario> LoginAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/ChangePassword", ReplyAction="http://tempuri.org/IMetodos/ChangePasswordResponse")]
        Web_SmartBuy.Service_User.Usuario ChangePassword(string UserName, string PassOld, string PassNew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/ChangePassword", ReplyAction="http://tempuri.org/IMetodos/ChangePasswordResponse")]
        System.Threading.Tasks.Task<Web_SmartBuy.Service_User.Usuario> ChangePasswordAsync(string UserName, string PassOld, string PassNew);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetodosChannel : Web_SmartBuy.Service_User.IMetodos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosClient : System.ServiceModel.ClientBase<Web_SmartBuy.Service_User.IMetodos>, Web_SmartBuy.Service_User.IMetodos {
        
        public MetodosClient() {
        }
        
        public MetodosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddClient(string Username, string Password) {
            return base.Channel.AddClient(Username, Password);
        }
        
        public System.Threading.Tasks.Task<bool> AddClientAsync(string Username, string Password) {
            return base.Channel.AddClientAsync(Username, Password);
        }
        
        public void UpdateInfo(string Username, string Nombre, string Apellidos, string Cedula, string Direccion, string Telefono, string CorreoElectronico) {
            base.Channel.UpdateInfo(Username, Nombre, Apellidos, Cedula, Direccion, Telefono, CorreoElectronico);
        }
        
        public System.Threading.Tasks.Task UpdateInfoAsync(string Username, string Nombre, string Apellidos, string Cedula, string Direccion, string Telefono, string CorreoElectronico) {
            return base.Channel.UpdateInfoAsync(Username, Nombre, Apellidos, Cedula, Direccion, Telefono, CorreoElectronico);
        }
        
        public void StateChange(string Username) {
            base.Channel.StateChange(Username);
        }
        
        public System.Threading.Tasks.Task StateChangeAsync(string Username) {
            return base.Channel.StateChangeAsync(Username);
        }
        
        public Web_SmartBuy.Service_User.Usuario Login(string Username, string Password) {
            return base.Channel.Login(Username, Password);
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_User.Usuario> LoginAsync(string Username, string Password) {
            return base.Channel.LoginAsync(Username, Password);
        }
        
        public Web_SmartBuy.Service_User.Usuario ChangePassword(string UserName, string PassOld, string PassNew) {
            return base.Channel.ChangePassword(UserName, PassOld, PassNew);
        }
        
        public System.Threading.Tasks.Task<Web_SmartBuy.Service_User.Usuario> ChangePasswordAsync(string UserName, string PassOld, string PassNew) {
            return base.Channel.ChangePasswordAsync(UserName, PassOld, PassNew);
        }
    }
}
